### ISSUE TITLE
Why https://github.com/marklawlor/react-session-hook is archived?

### ISSUE THREAD

**Issue by manishoctal** [marklawlor/typekitmanager#1]
Why https://github.com/marklawlor/react-session-hook is archived? I highly recommended using with react hook for the session. Did you see any other plugin for that? 
I am really waiting for a version update for this module.

**Comment by marklawlor** [comment]
Hey @manishoctal, I archived the project because its been over 2 years without maintenance and received little traction on npm. I would like to revisit it in the future, but I currently have higher priories.
